app_home:
    path:  /
    defaults: { _controller: "AppBundle:Note:index" }
    requirements:
        methods:  GET|POST

app_login:
    path:  /login
    defaults: { _controller: "AppBundle:Security:login" }
    requirements:
        methods:  GET|POST

app_registration:
    path:  /registration
    defaults: { _controller: "AppBundle:Security:registration" }
    requirements:
        methods:  GET|POST
